twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']
    paths:
        # point this wherever your css files live
#        '%kernel.project_dir%/assets/styles': styles
#        '%kernel.project_dir%/assets/vendor/bootstrap/dist/css': styles
        '%kernel.project_dir%/assets/styles': styles
        '%kernel.project_dir%/assets/images': images

when@test:
    twig:
        strict_variables: true
